version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mongodb://mongo:27017/ci_cd
    ports:
      - "7777:7777"
    depends_on:
      - mongo
    networks:
      - app-network
    volumes:
      - .:/app

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: ci_cd
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: